# Generated by Django 2.2.6 on 2019-12-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191218_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='move',
            name='player',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
