# Generated by Django 2.2.6 on 2019-12-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerooms',
            name='seats',
            field=models.IntegerField(default=2, max_length=10),
        ),
    ]
