# Generated by Django 2.2.6 on 2019-12-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gamerooms_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
