# Generated by Django 2.2.6 on 2019-12-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_move_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerooms',
            name='seats',
            field=models.IntegerField(default=2),
        ),
    ]
