# Generated by Django 2.2.6 on 2020-01-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200120_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerooms',
            name='seats',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
